# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'frhelper.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 984)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 372, 62))
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb_leader_name = QtWidgets.QComboBox(self.groupBox)
        self.cb_leader_name.setEditable(False)
        self.cb_leader_name.setObjectName("cb_leader_name")
        self.horizontalLayout.addWidget(self.cb_leader_name)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cb_researcher_name = QtWidgets.QComboBox(self.groupBox)
        self.cb_researcher_name.setEditable(False)
        self.cb_researcher_name.setObjectName("cb_researcher_name")
        self.horizontalLayout.addWidget(self.cb_researcher_name)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.LabelRole, self.horizontalLayout)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 1101, 841))
        self.groupBox_2.setObjectName("groupBox_2")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_2)
        self.tabWidget.setGeometry(QtCore.QRect(14, 19, 1081, 801))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 70, 331, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 311, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_sal_A = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_sal_A.setChecked(True)
        self.rb_sal_A.setObjectName("rb_sal_A")
        self.verticalLayout.addWidget(self.rb_sal_A)
        self.rb_sal_B = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_sal_B.setObjectName("rb_sal_B")
        self.verticalLayout.addWidget(self.rb_sal_B)
        self.rb_sal_C = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_sal_C.setObjectName("rb_sal_C")
        self.verticalLayout.addWidget(self.rb_sal_C)
        self.rb_sal_D = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_sal_D.setObjectName("rb_sal_D")
        self.verticalLayout.addWidget(self.rb_sal_D)
        self.rb_sal_E = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_sal_E.setObjectName("rb_sal_E")
        self.verticalLayout.addWidget(self.rb_sal_E)
        self.rb_sal_F = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.rb_sal_F.setObjectName("rb_sal_F")
        self.verticalLayout.addWidget(self.rb_sal_F)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 270, 331, 261))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 311, 233))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rb_job_A = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rb_job_A.setObjectName("rb_job_A")
        self.verticalLayout_2.addWidget(self.rb_job_A)
        self.rb_job_B = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rb_job_B.setObjectName("rb_job_B")
        self.verticalLayout_2.addWidget(self.rb_job_B)
        self.rb_job_C = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rb_job_C.setObjectName("rb_job_C")
        self.verticalLayout_2.addWidget(self.rb_job_C)
        self.rb_job_D = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rb_job_D.setObjectName("rb_job_D")
        self.verticalLayout_2.addWidget(self.rb_job_D)
        self.rb_job_E = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rb_job_E.setObjectName("rb_job_E")
        self.verticalLayout_2.addWidget(self.rb_job_E)
        self.rb_job_F = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rb_job_F.setObjectName("rb_job_F")
        self.verticalLayout_2.addWidget(self.rb_job_F)
        self.rb_job_G = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rb_job_G.setObjectName("rb_job_G")
        self.verticalLayout_2.addWidget(self.rb_job_G)
        self.rb_job_H = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rb_job_H.setObjectName("rb_job_H")
        self.verticalLayout_2.addWidget(self.rb_job_H)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.rb_job_I = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.rb_job_I.setObjectName("rb_job_I")
        self.horizontalLayout_13.addWidget(self.rb_job_I)
        self.le_other_job = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.le_other_job.setObjectName("le_other_job")
        self.horizontalLayout_13.addWidget(self.le_other_job)
        self.verticalLayout_2.addLayout(self.horizontalLayout_13)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(370, 70, 331, 181))
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_5)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 311, 161))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rb_deg_A = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.rb_deg_A.setObjectName("rb_deg_A")
        self.verticalLayout_3.addWidget(self.rb_deg_A)
        self.rb_deg_B = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.rb_deg_B.setObjectName("rb_deg_B")
        self.verticalLayout_3.addWidget(self.rb_deg_B)
        self.rb_deg_C = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.rb_deg_C.setObjectName("rb_deg_C")
        self.verticalLayout_3.addWidget(self.rb_deg_C)
        self.rb_deg_D = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.rb_deg_D.setObjectName("rb_deg_D")
        self.verticalLayout_3.addWidget(self.rb_deg_D)
        self.rb_deg_E = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.rb_deg_E.setObjectName("rb_deg_E")
        self.verticalLayout_3.addWidget(self.rb_deg_E)
        self.rb_deg_F = QtWidgets.QRadioButton(self.verticalLayoutWidget_3)
        self.rb_deg_F.setObjectName("rb_deg_F")
        self.verticalLayout_3.addWidget(self.rb_deg_F)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(370, 270, 331, 211))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox_6)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 19, 311, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.sb_job_breakfast_times = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sb_job_breakfast_times.setObjectName("sb_job_breakfast_times")
        self.gridLayout.addWidget(self.sb_job_breakfast_times, 0, 1, 1, 1)
        self.sb_job_lunch_times = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sb_job_lunch_times.setObjectName("sb_job_lunch_times")
        self.gridLayout.addWidget(self.sb_job_lunch_times, 1, 1, 1, 1)
        self.sb_job_supper_times = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.sb_job_supper_times.setObjectName("sb_job_supper_times")
        self.gridLayout.addWidget(self.sb_job_supper_times, 2, 1, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(730, 70, 331, 181))
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_7)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(9, 19, 311, 161))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.sb_restuarant_breakfast_times = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.sb_restuarant_breakfast_times.setObjectName("sb_restuarant_breakfast_times")
        self.gridLayout_2.addWidget(self.sb_restuarant_breakfast_times, 0, 1, 1, 1)
        self.sb_restuarant_lunch_times = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.sb_restuarant_lunch_times.setObjectName("sb_restuarant_lunch_times")
        self.gridLayout_2.addWidget(self.sb_restuarant_lunch_times, 1, 1, 1, 1)
        self.sb_restuarant_supper_times = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.sb_restuarant_supper_times.setObjectName("sb_restuarant_supper_times")
        self.gridLayout_2.addWidget(self.sb_restuarant_supper_times, 2, 1, 1, 1)
        self.sb_restuarant_meituan_times = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.sb_restuarant_meituan_times.setObjectName("sb_restuarant_meituan_times")
        self.gridLayout_2.addWidget(self.sb_restuarant_meituan_times, 3, 1, 1, 1)
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(730, 270, 331, 80))
        self.groupBox_8.setObjectName("groupBox_8")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_8)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(9, 19, 311, 51))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.sb_other_family_times = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.sb_other_family_times.setObjectName("sb_other_family_times")
        self.gridLayout_3.addWidget(self.sb_other_family_times, 0, 1, 1, 1)
        self.pb_add_to_B0 = QtWidgets.QPushButton(self.tab)
        self.pb_add_to_B0.setGeometry(QtCore.QRect(770, 410, 251, 51))
        self.pb_add_to_B0.setObjectName("pb_add_to_B0")
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(10, 20, 331, 31))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_12.addWidget(self.label_3)
        self.le_query_name = QtWidgets.QLineEdit(self.horizontalLayoutWidget_11)
        self.le_query_name.setObjectName("le_query_name")
        self.horizontalLayout_12.addWidget(self.le_query_name)
        self.tableWidget = QtWidgets.QTableWidget(self.tab)
        self.tableWidget.setGeometry(QtCore.QRect(10, 560, 1051, 151))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(16)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(15, item)
        self.label_50 = QtWidgets.QLabel(self.tab)
        self.label_50.setGeometry(QtCore.QRect(10, 539, 191, 16))
        self.label_50.setObjectName("label_50")
        self.pb_save_B0 = QtWidgets.QPushButton(self.tab)
        self.pb_save_B0.setGeometry(QtCore.QRect(510, 730, 93, 28))
        self.pb_save_B0.setObjectName("pb_save_B0")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(340, 20, 441, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_2.addWidget(self.label_13)
        self.rb_day1_B1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.rb_day1_B1.setObjectName("rb_day1_B1")
        self.horizontalLayout_2.addWidget(self.rb_day1_B1)
        self.rb_day2_B1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.rb_day2_B1.setObjectName("rb_day2_B1")
        self.horizontalLayout_2.addWidget(self.rb_day2_B1)
        self.rb_day3_B1 = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.rb_day3_B1.setObjectName("rb_day3_B1")
        self.horizontalLayout_2.addWidget(self.rb_day3_B1)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(790, 20, 281, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_3.addWidget(self.label_14)
        self.de_B1 = QtWidgets.QDateEdit(self.horizontalLayoutWidget_2)
        self.de_B1.setObjectName("de_B1")
        self.horizontalLayout_3.addWidget(self.de_B1)
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 80, 341, 131))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_4.addWidget(self.label_18, 3, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 161))
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 1, 0, 1, 1)
        self.l_num_B1 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.l_num_B1.setObjectName("l_num_B1")
        self.gridLayout_4.addWidget(self.l_num_B1, 0, 1, 1, 1)
        self.cb_meal_time_B1 = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.cb_meal_time_B1.setObjectName("cb_meal_time_B1")
        self.cb_meal_time_B1.addItem("")
        self.cb_meal_time_B1.addItem("")
        self.cb_meal_time_B1.addItem("")
        self.gridLayout_4.addWidget(self.cb_meal_time_B1, 1, 1, 1, 1)
        self.cb_food_place_B1 = QtWidgets.QComboBox(self.gridLayoutWidget_4)
        self.cb_food_place_B1.setEditable(True)
        self.cb_food_place_B1.setObjectName("cb_food_place_B1")
        self.cb_food_place_B1.addItem("")
        self.cb_food_place_B1.addItem("")
        self.cb_food_place_B1.addItem("")
        self.cb_food_place_B1.addItem("")
        self.cb_food_place_B1.addItem("")
        self.gridLayout_4.addWidget(self.cb_food_place_B1, 3, 1, 1, 1)
        self.le_food_name_B1 = QtWidgets.QLineEdit(self.gridLayoutWidget_4)
        self.le_food_name_B1.setObjectName("le_food_name_B1")
        self.gridLayout_4.addWidget(self.le_food_name_B1, 2, 1, 1, 1)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 220, 301, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.rb_personal = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.rb_personal.setObjectName("rb_personal")
        self.horizontalLayout_4.addWidget(self.rb_personal)
        self.rb_family = QtWidgets.QRadioButton(self.horizontalLayoutWidget_3)
        self.rb_family.setObjectName("rb_family")
        self.horizontalLayout_4.addWidget(self.rb_family)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_2.setGeometry(QtCore.QRect(340, 80, 731, 192))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(5)
        self.tableWidget_2.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(10, 420, 181, 16))
        self.label_20.setObjectName("label_20")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget_3.setGeometry(QtCore.QRect(10, 440, 1061, 271))
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(16)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(15, item)
        self.pb_save_B1 = QtWidgets.QPushButton(self.tab_2)
        self.pb_save_B1.setGeometry(QtCore.QRect(510, 730, 93, 28))
        self.pb_save_B1.setObjectName("pb_save_B1")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.tab_2)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(10, 20, 301, 31))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_14.addWidget(self.label_12)
        self.cb_query_name_B1 = QtWidgets.QComboBox(self.horizontalLayoutWidget_13)
        self.cb_query_name_B1.setObjectName("cb_query_name_B1")
        self.horizontalLayout_14.addWidget(self.cb_query_name_B1)
        self.pb_add_to_B1 = QtWidgets.QPushButton(self.tab_2)
        self.pb_add_to_B1.setGeometry(QtCore.QRect(420, 340, 211, 41))
        self.pb_add_to_B1.setObjectName("pb_add_to_B1")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayoutWidget_9 = QtWidgets.QWidget(self.tab_3)
        self.gridLayoutWidget_9.setGeometry(QtCore.QRect(10, 80, 341, 131))
        self.gridLayoutWidget_9.setObjectName("gridLayoutWidget_9")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.gridLayoutWidget_9)
        self.gridLayout_9.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_39 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_39.setObjectName("label_39")
        self.gridLayout_9.addWidget(self.label_39, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_40.setObjectName("label_40")
        self.gridLayout_9.addWidget(self.label_40, 3, 0, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_41.setMaximumSize(QtCore.QSize(16777215, 161))
        self.label_41.setObjectName("label_41")
        self.gridLayout_9.addWidget(self.label_41, 2, 0, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.label_42.setObjectName("label_42")
        self.gridLayout_9.addWidget(self.label_42, 1, 0, 1, 1)
        self.l_num_B2 = QtWidgets.QLabel(self.gridLayoutWidget_9)
        self.l_num_B2.setObjectName("l_num_B2")
        self.gridLayout_9.addWidget(self.l_num_B2, 0, 1, 1, 1)
        self.cb_meal_time_B2 = QtWidgets.QComboBox(self.gridLayoutWidget_9)
        self.cb_meal_time_B2.setObjectName("cb_meal_time_B2")
        self.cb_meal_time_B2.addItem("")
        self.cb_meal_time_B2.addItem("")
        self.cb_meal_time_B2.addItem("")
        self.gridLayout_9.addWidget(self.cb_meal_time_B2, 1, 1, 1, 1)
        self.cb_food_place_B2 = QtWidgets.QComboBox(self.gridLayoutWidget_9)
        self.cb_food_place_B2.setEditable(True)
        self.cb_food_place_B2.setObjectName("cb_food_place_B2")
        self.cb_food_place_B2.addItem("")
        self.cb_food_place_B2.addItem("")
        self.cb_food_place_B2.addItem("")
        self.cb_food_place_B2.addItem("")
        self.cb_food_place_B2.addItem("")
        self.gridLayout_9.addWidget(self.cb_food_place_B2, 3, 1, 1, 1)
        self.le_food_name_B2 = QtWidgets.QLineEdit(self.gridLayoutWidget_9)
        self.le_food_name_B2.setObjectName("le_food_name_B2")
        self.gridLayout_9.addWidget(self.le_food_name_B2, 2, 1, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.tab_3)
        self.label_44.setGeometry(QtCore.QRect(10, 420, 171, 16))
        self.label_44.setObjectName("label_44")
        self.pb_save_B2 = QtWidgets.QPushButton(self.tab_3)
        self.pb_save_B2.setGeometry(QtCore.QRect(510, 730, 93, 28))
        self.pb_save_B2.setObjectName("pb_save_B2")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(340, 20, 441, 31))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_45 = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_9.addWidget(self.label_45)
        self.rb_day1_B2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_8)
        self.rb_day1_B2.setObjectName("rb_day1_B2")
        self.horizontalLayout_9.addWidget(self.rb_day1_B2)
        self.rb_day2_B2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_8)
        self.rb_day2_B2.setObjectName("rb_day2_B2")
        self.horizontalLayout_9.addWidget(self.rb_day2_B2)
        self.rb_day3_B2 = QtWidgets.QRadioButton(self.horizontalLayoutWidget_8)
        self.rb_day3_B2.setObjectName("rb_day3_B2")
        self.horizontalLayout_9.addWidget(self.rb_day3_B2)
        self.tableWidget_7 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_7.setGeometry(QtCore.QRect(10, 440, 1061, 271))
        self.tableWidget_7.setObjectName("tableWidget_7")
        self.tableWidget_7.setColumnCount(8)
        self.tableWidget_7.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_7.setHorizontalHeaderItem(7, item)
        self.tableWidget_8 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_8.setGeometry(QtCore.QRect(340, 80, 731, 192))
        self.tableWidget_8.setObjectName("tableWidget_8")
        self.tableWidget_8.setColumnCount(5)
        self.tableWidget_8.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_8.setHorizontalHeaderItem(4, item)
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(790, 20, 281, 31))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_47 = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_10.addWidget(self.label_47)
        self.de_B2 = QtWidgets.QDateEdit(self.horizontalLayoutWidget_9)
        self.de_B2.setObjectName("de_B2")
        self.horizontalLayout_10.addWidget(self.de_B2)
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(340, 280, 491, 31))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_48 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_11.addWidget(self.label_48)
        self.dsb_food_weight = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget_10)
        self.dsb_food_weight.setObjectName("dsb_food_weight")
        self.horizontalLayout_11.addWidget(self.dsb_food_weight)
        self.label_49 = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.label_49.setObjectName("label_49")
        self.horizontalLayout_11.addWidget(self.label_49)
        self.cb_weight_unit = QtWidgets.QComboBox(self.horizontalLayoutWidget_10)
        self.cb_weight_unit.setObjectName("cb_weight_unit")
        self.cb_weight_unit.addItem("")
        self.cb_weight_unit.addItem("")
        self.horizontalLayout_11.addWidget(self.cb_weight_unit)
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(10, 20, 301, 31))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_51 = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.label_51.setObjectName("label_51")
        self.horizontalLayout_15.addWidget(self.label_51)
        self.cb_query_name_B2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_14)
        self.cb_query_name_B2.setObjectName("cb_query_name_B2")
        self.horizontalLayout_15.addWidget(self.cb_query_name_B2)
        self.pb_add_to_B2 = QtWidgets.QPushButton(self.tab_3)
        self.pb_add_to_B2.setGeometry(QtCore.QRect(420, 340, 211, 41))
        self.pb_add_to_B2.setObjectName("pb_add_to_B2")
        self.tabWidget.addTab(self.tab_3, "")
        self.pb_create_data = QtWidgets.QPushButton(self.centralwidget)
        self.pb_create_data.setGeometry(QtCore.QRect(410, 35, 131, 30))
        self.pb_create_data.setObjectName("pb_create_data")
        self.pb_load_data = QtWidgets.QPushButton(self.centralwidget)
        self.pb_load_data.setGeometry(QtCore.QRect(560, 35, 131, 30))
        self.pb_load_data.setObjectName("pb_load_data")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1120, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.pb_create_data.clicked.connect(MainWindow.func_create_researcher_data)
        self.pb_load_data.clicked.connect(MainWindow.func_load_researcher_data)
        self.pb_add_to_B0.clicked.connect(MainWindow.func_add_to_B0)
        self.pb_save_B0.clicked.connect(MainWindow.func_save_B0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "调查数据录入小助手"))
        self.groupBox.setTitle(_translate("MainWindow", "调研小组信息"))
        self.label.setText(_translate("MainWindow", "院所-组长："))
        self.label_2.setText(_translate("MainWindow", "调查员："))
        self.groupBox_2.setTitle(_translate("MainWindow", "被调查对象信息"))
        self.groupBox_3.setTitle(_translate("MainWindow", "（1）被调查者家庭年收入："))
        self.rb_sal_A.setText(_translate("MainWindow", "（A）2万以下（包含2万）"))
        self.rb_sal_B.setText(_translate("MainWindow", "（B）大于2万到小于等于5万"))
        self.rb_sal_C.setText(_translate("MainWindow", "（C）大于5万到小于等于10万"))
        self.rb_sal_D.setText(_translate("MainWindow", "（D）大于10万到小于等于20万"))
        self.rb_sal_E.setText(_translate("MainWindow", "（E）大于20万到小于等于50万"))
        self.rb_sal_F.setText(_translate("MainWindow", "（F）50万以上"))
        self.groupBox_4.setTitle(_translate("MainWindow", "（2）被调查者本人工作类型："))
        self.rb_job_A.setText(_translate("MainWindow", "（A）公职人员（公务员或事业单位人员）"))
        self.rb_job_B.setText(_translate("MainWindow", "（B）国企员工"))
        self.rb_job_C.setText(_translate("MainWindow", "（C）外企员工"))
        self.rb_job_D.setText(_translate("MainWindow", "（D）民营企业、集体企业员工"))
        self.rb_job_E.setText(_translate("MainWindow", "（E）个体经营者"))
        self.rb_job_F.setText(_translate("MainWindow", "（F）农民"))
        self.rb_job_G.setText(_translate("MainWindow", "（G）离退休及无工作人员"))
        self.rb_job_H.setText(_translate("MainWindow", "（H）学生"))
        self.rb_job_I.setText(_translate("MainWindow", "（I）其他："))
        self.groupBox_5.setTitle(_translate("MainWindow", "（3）被调查者本人学历："))
        self.rb_deg_A.setText(_translate("MainWindow", "（A）小学文化及其以下"))
        self.rb_deg_B.setText(_translate("MainWindow", "（B）初中文化"))
        self.rb_deg_C.setText(_translate("MainWindow", "（C）高中文化和高等职业高中"))
        self.rb_deg_D.setText(_translate("MainWindow", "（D）本科学历"))
        self.rb_deg_E.setText(_translate("MainWindow", "（E）硕士学历"))
        self.rb_deg_F.setText(_translate("MainWindow", "（F）博士学历"))
        self.groupBox_6.setTitle(_translate("MainWindow", "（4）被调查者本人每月在校或单位就餐次数："))
        self.label_6.setText(_translate("MainWindow", "早餐（次）："))
        self.label_4.setText(_translate("MainWindow", "午餐（次）："))
        self.label_5.setText(_translate("MainWindow", "晚餐（次）："))
        self.groupBox_7.setTitle(_translate("MainWindow", "（5）被调查者本人每月在餐饮单位就餐次数："))
        self.label_8.setText(_translate("MainWindow", "午餐（次）："))
        self.label_10.setText(_translate("MainWindow", "其中使用美团平台次数："))
        self.label_7.setText(_translate("MainWindow", "早餐（次）："))
        self.label_9.setText(_translate("MainWindow", "晚餐（次）："))
        self.groupBox_8.setTitle(_translate("MainWindow", "（6）被调查者每月在其他家庭就餐次数："))
        self.label_11.setText(_translate("MainWindow", "次数："))
        self.pb_add_to_B0.setText(_translate("MainWindow", "增加到被调查居民信息问卷汇总"))
        self.label_3.setText(_translate("MainWindow", "被调查者姓名："))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IntervieweeIDString"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "SourceFolder"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Interviewer"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "IntervieweeSeqID"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "IntervieweeName"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Q1_Income"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Q2_Vocation"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Q3_Education"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Q4_MealAtWork_Breakfast"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Q4_MealAtWork_Lunch"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Q4_MealAtWork_Dinner"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Q5_MealOut_Breakfast"))
        item = self.tableWidget.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Q5_MealOut_Lunch"))
        item = self.tableWidget.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Q5_MealOut_Dinner"))
        item = self.tableWidget.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Q5_Meituan"))
        item = self.tableWidget.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Q6_MealOutOtherFamily"))
        self.label_50.setText(_translate("MainWindow", "被调查居民问卷信息汇总："))
        self.pb_save_B0.setText(_translate("MainWindow", "保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "B0被调查对象基本信息"))
        self.label_13.setText(_translate("MainWindow", "调查日："))
        self.rb_day1_B1.setText(_translate("MainWindow", "第一天"))
        self.rb_day2_B1.setText(_translate("MainWindow", "第二天"))
        self.rb_day3_B1.setText(_translate("MainWindow", "第三天"))
        self.label_14.setText(_translate("MainWindow", "调查日期："))
        self.label_15.setText(_translate("MainWindow", "1.编号："))
        self.label_18.setText(_translate("MainWindow", "4.进餐地点："))
        self.label_17.setText(_translate("MainWindow", "3.食物名称："))
        self.label_16.setText(_translate("MainWindow", "2.进餐时间："))
        self.l_num_B1.setText(_translate("MainWindow", "TextLabel"))
        self.cb_meal_time_B1.setItemText(0, _translate("MainWindow", "1 早餐"))
        self.cb_meal_time_B1.setItemText(1, _translate("MainWindow", "2 午餐"))
        self.cb_meal_time_B1.setItemText(2, _translate("MainWindow", "3 晚餐"))
        self.cb_food_place_B1.setItemText(0, _translate("MainWindow", "1 在家"))
        self.cb_food_place_B1.setItemText(1, _translate("MainWindow", "2 学校或工作单位"))
        self.cb_food_place_B1.setItemText(2, _translate("MainWindow", "3 饭店、快餐店、咖啡厅、摊点"))
        self.cb_food_place_B1.setItemText(3, _translate("MainWindow", "4 亲戚或朋友家"))
        self.cb_food_place_B1.setItemText(4, _translate("MainWindow", "5 请具体说明"))
        self.rb_personal.setText(_translate("MainWindow", "本人消费"))
        self.rb_family.setText(_translate("MainWindow", "家庭消费"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "成分名称"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "成分类别"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "成分重量"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "单位"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "备注"))
        self.label_20.setText(_translate("MainWindow", "被调查者B1统计分析表："))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IntervieweeIDString"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MealDay"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Q1_SeqNum"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Q2_MealTime"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Q3_FoodName"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Q4_MealPlace"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Q51_Self_FoodCategory"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Q51_Self_FoodIngredient"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Q51_Amount1"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Q51_Amount2"))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Q52_Family_FoodCategory"))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Q52_Family_FoodIngredient"))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Q52_Amount1"))
        item = self.tableWidget_3.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Q52_Amount2"))
        item = self.tableWidget_3.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Q52_SelfRatio"))
        item = self.tableWidget_3.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "Q_Memo"))
        self.pb_save_B1.setText(_translate("MainWindow", "保存"))
        self.label_12.setText(_translate("MainWindow", "被调查者姓名："))
        self.pb_add_to_B1.setText(_translate("MainWindow", "增加食物到B1统计表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "B1正餐问卷"))
        self.label_39.setText(_translate("MainWindow", "1.编号："))
        self.label_40.setText(_translate("MainWindow", "4.进餐地点："))
        self.label_41.setText(_translate("MainWindow", "3.食物名称："))
        self.label_42.setText(_translate("MainWindow", "2.进餐时间："))
        self.l_num_B2.setText(_translate("MainWindow", "TextLabel"))
        self.cb_meal_time_B2.setItemText(0, _translate("MainWindow", "1 早餐"))
        self.cb_meal_time_B2.setItemText(1, _translate("MainWindow", "2 午餐"))
        self.cb_meal_time_B2.setItemText(2, _translate("MainWindow", "3 晚餐"))
        self.cb_food_place_B2.setItemText(0, _translate("MainWindow", "1 在家"))
        self.cb_food_place_B2.setItemText(1, _translate("MainWindow", "2 学校或工作单位"))
        self.cb_food_place_B2.setItemText(2, _translate("MainWindow", "3 饭店、快餐店、咖啡厅、摊点"))
        self.cb_food_place_B2.setItemText(3, _translate("MainWindow", "4 亲戚或朋友家"))
        self.cb_food_place_B2.setItemText(4, _translate("MainWindow", "5 请具体说明"))
        self.label_44.setText(_translate("MainWindow", "被调查者B2统计分析表："))
        self.pb_save_B2.setText(_translate("MainWindow", "保存"))
        self.label_45.setText(_translate("MainWindow", "调查日："))
        self.rb_day1_B2.setText(_translate("MainWindow", "第一天"))
        self.rb_day2_B2.setText(_translate("MainWindow", "第二天"))
        self.rb_day3_B2.setText(_translate("MainWindow", "第三天"))
        item = self.tableWidget_7.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "IntervieweeIDString"))
        item = self.tableWidget_7.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "MealDay"))
        item = self.tableWidget_7.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Q1_SeqNum"))
        item = self.tableWidget_7.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Q2_MealTime"))
        item = self.tableWidget_7.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Q3_FoodName"))
        item = self.tableWidget_7.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Q4_MealPlace"))
        item = self.tableWidget_7.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Q_SnackAmount1"))
        item = self.tableWidget_7.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Q_SnackAmount2"))
        item = self.tableWidget_8.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "新建行"))
        item = self.tableWidget_8.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "成分名称"))
        item = self.tableWidget_8.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "成分类别"))
        item = self.tableWidget_8.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "成分重量"))
        item = self.tableWidget_8.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "单位"))
        item = self.tableWidget_8.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "备注"))
        self.label_47.setText(_translate("MainWindow", "调查日期："))
        self.label_48.setText(_translate("MainWindow", "小食/饮料重量："))
        self.label_49.setText(_translate("MainWindow", "小食/饮料单位："))
        self.cb_weight_unit.setItemText(0, _translate("MainWindow", "g"))
        self.cb_weight_unit.setItemText(1, _translate("MainWindow", "ml"))
        self.label_51.setText(_translate("MainWindow", "被调查者姓名："))
        self.pb_add_to_B2.setText(_translate("MainWindow", "增加食物到B2统计表"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "B2零食问卷"))
        self.pb_create_data.setText(_translate("MainWindow", "创建调查员数据"))
        self.pb_load_data.setText(_translate("MainWindow", "载入调查员数据"))

